lolbox/models.py
# coding: utf-8
import time
from mongoengine import *
import os
from flask import current_app
from flask.ext.login import UserMixin, AnonymousUserMixin
from app import login_manager

MONGODB_URI = os.environ.get("MONGODB_URI")
MONGODB_SETTINGS = {}
MONGODB_SETTINGS['db'] = MONGODB_URI.split("/")[-1]
MONGODB_SETTINGS['host'] = MONGODB_URI

connect(MONGODB_SETTINGS['db'], host=MONGODB_SETTINGS['host'])

class Post(Document):
    text = StringField(verbose_name=u"текст")
    file_id = StringField(verbose_name=u"id файла", help_text=u"id файла, данное при загрузки в S3")
    file_name = StringField(verbose_name=u"файл", help_text=u"имя файла")
    time = FloatField(default=time.time, verbose_name=u"время", help_text=u"время создания поста")
    author = StringField(verbose_name=u"автор", help_text=u"id автора поста")

class User(Document):
    username = StringField(verbose_name=u"никнейм", unique=True)
    email = EmailField(unique=True, verbose_name=u"email")
    password = StringField(verbose_name=u"пароль")
    is_admin = BooleanField(verbose_name=u"администратор?", default=False)
    member_since = FloatField(default=time.time, verbose_name=u"время регистрации")
    location = StringField(verbose_name=u"месторасположение")
    name = StringField(verbose_name=u"имя")

    def is_authenticated(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

    def is_active(self):
        return True

    @staticmethod
    def verify_password(password_hash, password):
        return password == password_hash

class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

@login_manager.user_loader
def load_user(id):
    return User.objects.get(id=id)

lolbox/app.py
# coding: utf-8

from flask import Flask, render_template, request, abort
import time
from flask.ext.login import LoginManager, current_user

app = Flask(__name__)
app.config.from_object('config')
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message = u"Сайт находится в закрытой разработке. Вход только по приглашениям."
login_manager.init_app(app)

@app.errorhandler(404)
def page_not_found(e):
        return render_template('404.html'), 404

@app.errorhandler(500)
def internal_server_error(e):
        return render_template('500.html'), 500

@app.before_request
def check_login():
        if request.endpoint == 'admin.index':
                if current_user.is_authenticated and current_user.is_admin:
                                return
                abort(404)

from lolbox.models import *
@app.template_filter('id_to_username')
def id_to_username(id):
        return User.objects.get(id=str(id))['username']

from lolbox.views import home
from lolbox.views import auth
from lolbox.views import admin

app.register_blueprint(home.home)
app.register_blueprint(auth.auth)
app.register_blueprint(admin.admin_panel)

lolbox/views/admin.py
from flask import Blueprint, render_template, request, redirect, abort, url_for
from lolbox.models import *
from lolbox.app import app
from flask.ext.login import login_user, logout_user, login_required, current_user
from flask.ext.superadmin import *

admin_panel = Blueprint('admin_panel', __name__)

class AuthMixin(object):
    def is_accessible(self):
        if current_user.is_authenticated and current_user.is_admin:
            return True
        return False

    def _handle_view(self, name, *args, **kwargs):
        if not self.is_accessible():
            abort(404)

class UserModel(AuthMixin, model.ModelAdmin):
    list_display = ('username','email', 'id')

class PostModel(AuthMixin, model.ModelAdmin):
    list_display = ('text', 'author')

admin = Admin(app, 'lolbox')

admin.register(User, UserModel)
admin.register(Post, PostModel)

lolbox/views/auth.py
# coding: utf-8

from flask import Blueprint, render_template, current_app, request, flash, redirect, url_for
from lolbox.models import *
from flask.ext.login import login_user, logout_user, login_required, current_user

auth = Blueprint('auth', __name__)

@auth.route('/signin', methods=['GET'])
def signin():
    return render_template('auth/signin.html')

@auth.route('/signin', methods=['POST'])
def login():
    password = request.form["password"]
    email = request.form["email"]
    user = User.objects.get(email=email)
    remember_me = False
    if 'remember' in request.form:
        remember_me = True
    if user is not None and user.verify_password(password, user.password):
        login_user(user, remember_me)
        return redirect(url_for('home.index'))

    flash(u"Неверный Email или пароль.")
    return render_template('auth/signin.html')

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home.index'))

lolbox/views/home.py
from flask import Blueprint, render_template, request, redirect
from lolbox.models import *
from flask.ext.login import login_required, current_user

home = Blueprint('home', __name__)

@home.route('/', methods=['GET'])
@login_required
def index():
        posts = Post.objects.all()
        return render_template('home/index.html', posts=posts)

@home.route('/', methods=['POST'])
@login_required
def new_post():
        text = request.form["text"]
        post = Post(text=text, author=str(current_user.id))
        post.save()
        return redirect(request.path)

@home.route('/rules')
def rules():
        return render_template('home/rules.html')

lolbox/templates/home/index.html
{% extends "layout.html" %}

{% block page_content %}
<script src="{{ url_for('static', filename='bower_components/react/react.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/react/react-dom.js') }}"></script>

<title>lolbox - spread everything</title>

<div id="main"></div>

<div class="panel panel-default">
    <div class="panel-body">
        <form method="post" role="form">
            <div class="form-group">
                <textarea required id="text" class="form-control" name="text" placeholder="что нового?" maxlength="100"></textarea>
                <small><span id="chars">100</span> символов осталось</small>
                <p></p>
            </div>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                Опубликовать</button>
            <script>
             $(document).ready(function() {
                 $('button').attr('disabled', true);
                 $('textarea').keypress(function(e){
                     if (e.keyCode == 13) return false
                 })
                 $('textarea').on('keyup',function() {
                     var textarea_value = $("#text").val();
                     if(textarea_value != '') {
                         $('button').attr('disabled' , false);
                     }else{
                         $('button').attr('disabled' , true);
                     }});
                 var maxLength = 100;
                 $('textarea').keyup(function() {
                     var length = $(this).val().length;
                     var length = maxLength-length;
                     $('#chars').text(length);
                 });
             });
            </script>
        </form>
    </div>
</div>

<script>
    function tm(unix_tm) {
        var dt = new Date(unix_tm*1000);
        document.writeln(dt.toLocaleString("ru"));
    }
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-flash" aria-hidden="true"></span> Свежие посты</div>
    <div class="panel-body">
        {% for post in posts|reverse%}
        <div class="panel panel-default">
            <div class="panel-body">
                <h5><strong>{{ post.author|id_to_username }}</strong> <span class="label label-default"><script>tm({{post.time}})</script></span></h5>
                {{post.text}}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock %}

lolbox/templates/home/rules.html
{% extends "layout.html" %}

{% block page_content %}
<title>lolbox - правила</title>

<div class="page-header">
    <h3>Правила</h3>
</div>
<p>1. Правил нет (пока...).</p>
<p>2. Посты не несущие никакого смысла будут удаляться без предупреждения со стороны администрации.</p>
{% endblock %}

lolbox/templates/index.html
{% extends "layout.html" %}

{% block page_content %}
<script src="{{ url_for('static', filename='bower_components/react/react.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/react/react-dom.js') }}"></script>

<title>lolbox - spread everything</title>

<div id="main"></div>

<div class="panel panel-default">
    <div class="panel-body">
        <form method="post" role="form">
            <div class="form-group">
                <textarea required id="text" class="form-control" name="text" placeholder="что нового?" maxlength="100"></textarea>
                <small><span id="chars">100</span> символов осталось</small>
                <p></p>
            </div>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                Опубликовать</button>
            <script>
             $(document).ready(function() {
                 $('button').attr('disabled', true);
                 $('textarea').keypress(function(e){
                     if (e.keyCode == 13) return false
                 })
                 $('textarea').on('keyup',function() {
                     var textarea_value = $("#text").val();
                     if(textarea_value != '') {
                         $('button').attr('disabled' , false);
                     }else{
                         $('button').attr('disabled' , true);
                     }});
                 var maxLength = 100;
                 $('textarea').keyup(function() {
                     var length = $(this).val().length;
                     var length = maxLength-length;
                     $('#chars').text(length);
                 });
             });
            </script>
        </form>
    </div>
</div>

<script>
    function tm(unix_tm) {
        var dt = new Date(unix_tm*1000);
        document.writeln(dt.toLocaleString("ru"));
    }
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-flash" aria-hidden="true"></span> Свежие посты</div>
    <div class="panel-body">
        {% for post in posts%}
        <div class="panel panel-default">
            <div class="panel-body">
                <h5><strong>{{post.author|id_to_username}}</strong> <span class="label label-default"><script>tm({{post.time}})</script></span></h5>
                {{post.text}}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock %}

lolbox/templates/layout.html
{% block head %}

<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<!-- Latest compiled and minified CSS -->
<link href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/main.css') }}"" rel="stylesheet">
<!-- Latest compiled and minified JavaScript -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
	 	<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
			  </button>
		</div>
    <div class="container">
		    <div class="navbar-collapse collapse">
				    <ul class="nav navbar-nav">
						    <li><a href="{{ url_for('home.index') }}">Главная</a></li>
                <li><a href="{{ url_for('home.rules') }}">Правила</a></li>
				    </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {{ current_user.username }} <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        {% if current_user.is_admin %}
                        <li><a href="{{ url_for('admin.index') }}">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                            Панель администрирования</a></li>
                        {% endif %}
                        <li>
                            <a href="{{ url_for('auth.logout') }}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Выйти</a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li>
                    <p class="navbar-btn">
                        <a href="{{ url_for('auth.signin') }}" class="btn btn-primary">Войти</a>
                    </p>
                </li>
                {% endif %}
            </ul>
		    </div>
	  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
</div>
{% endblock %}